default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] if ENV['DATABASE_URL'].present? %>

development:
  <<: *default
  database: tourism_weather_development

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_URL'] || 'tourism_weather_test' %>

production:
  <<: *default

# Action Cable
cable:
  <<: *default
